name: daen
description: تطبيق دائن لإدارة الديون والدفعات.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  share_plus: ^10.1.0
  pdf: ^3.11.0
  printing: ^5.13.0

flutter:
  uses-material-design: true
